# Generated by Django 3.0.8 on 2021-02-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_merchitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('quanity', models.IntegerField()),
            ],
        ),
    ]
