# Generated by Django 3.0.8 on 2021-02-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merchorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_line_one', models.CharField(max_length=200)),
                ('item_line_two', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='merchitem',
            old_name='item_name',
            new_name='item_line_one',
        ),
        migrations.AddField(
            model_name='merchitem',
            name='item_line_two',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
    ]
