# Generated by Django 3.0.8 on 2021-02-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210203_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchfeature',
            old_name='description',
            new_name='description_one',
        ),
        migrations.AddField(
            model_name='merchfeature',
            name='description_two',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchitem',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
