# Generated by Django 3.0.8 on 2021-04-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210302_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_name', models.CharField(max_length=200)),
                ('banner_pic', models.CharField(max_length=200)),
                ('background_color', models.CharField(max_length=200)),
                ('text_color', models.CharField(max_length=200)),
                ('button_color', models.CharField(max_length=200)),
                ('button_text_color', models.CharField(max_length=200)),
                ('pic_one', models.CharField(max_length=200)),
                ('pic_two', models.CharField(max_length=200)),
                ('pic_three', models.CharField(max_length=200)),
                ('video_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_name', models.CharField(max_length=200)),
                ('production_one', models.CharField(max_length=200)),
                ('production_two', models.CharField(max_length=200)),
                ('production_three', models.CharField(max_length=200)),
                ('mixing_one', models.CharField(max_length=200)),
                ('mixing_two', models.CharField(max_length=200)),
                ('mixing_three', models.CharField(max_length=200)),
                ('features_one', models.CharField(max_length=200)),
                ('features_two', models.CharField(max_length=200)),
                ('features_three', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='merchorder',
            name='quanity',
            field=models.PositiveIntegerField(),
        ),
    ]
