# Generated by Django 3.0.8 on 2021-05-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210420_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='bio',
            field=models.TextField(default='temp bio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchfeature',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
