# Generated by Django 3.0.8 on 2021-05-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210501_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchitem',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
